[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"

[[functions]]
  name = "rss-update-weekly"
  src = "netlify/functions/rss-update-weekly.js"
  schedule = "0 0 * * 1"  # Run every Monday at midnight

[functions]
  # Enable serverless functions
  included_files = ["data/**/*"]

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
